import { ReturnRequest, BatchRiskTelemetry, OperationalImpactMetrics } from "./types";

export interface PresetScenario {
  id: string;
  badge: string;
  badgeColor: "cyan" | "emerald" | "amber" | "rose" | "purple";
  title: string;
  subtitle: string;
  scenarioDescription: string;
  expectedOutcome: string;
  request: ReturnRequest;
  sampleImage: string;
}

export const INITIAL_BATCH_TELEMETRY: Record<string, BatchRiskTelemetry> = {
  "BATCH-2026-08": {
    batchId: "BATCH-2026-08",
    sku: "SHOE-AERO-08",
    productName: "AeroFlow Velocity Runner X",
    vendorId: "VEND-APEX-09",
    vendorName: "Apex Footwear Ltd",
    totalUnitsSold: 320,
    totalReturnsReported: 7,
    historicalDefectRate: 0.032, // 3.2%
    currentDefectRate: 0.032,
    riskLevel: "LOW",
    isQuarantined: false,
    quarantinedUnitsCount: 0,
    topDefectCluster: "Sole Separation",
    clusterDefectPercentage: 42,
    gmvAtRiskInr: 212415,
  },
  "BATCH-2026-04J": {
    batchId: "BATCH-2026-04J",
    sku: "JKT-BOMB-04",
    productName: "Midnight Leather Bomber Jacket",
    vendorId: "VEND-NORTH-04",
    vendorName: "NorthStar Apparels",
    totalUnitsSold: 210,
    totalReturnsReported: 14,
    historicalDefectRate: 0.085, // 8.5%
    currentDefectRate: 0.085,
    riskLevel: "ELEVATING",
    isQuarantined: false,
    quarantinedUnitsCount: 0,
    topDefectCluster: "Zipper Teeth Splitting",
    clusterDefectPercentage: 68,
    gmvAtRiskInr: 332405,
  },
  "BATCH-2026-11T": {
    batchId: "BATCH-2026-11T",
    sku: "TEE-ACT-11",
    productName: "ActiveFit Breathable Compression Tee",
    vendorId: "VEND-KNIT-02",
    vendorName: "KnitCraft Global",
    totalUnitsSold: 540,
    totalReturnsReported: 18,
    historicalDefectRate: 0.033,
    currentDefectRate: 0.033,
    riskLevel: "LOW",
    isQuarantined: false,
    quarantinedUnitsCount: 0,
    topDefectCluster: "Size Runs Small",
    clusterDefectPercentage: 82,
    gmvAtRiskInr: 127840,
  },
  "BATCH-2026-ACC": {
    batchId: "BATCH-2026-ACC",
    sku: "ACC-MOUNT-01",
    productName: "UltraGrip Windshield Phone Mount",
    vendorId: "VEND-VOLT-07",
    vendorName: "VoltGear Supplies",
    totalUnitsSold: 850,
    totalReturnsReported: 29,
    historicalDefectRate: 0.034,
    currentDefectRate: 0.034,
    riskLevel: "LOW",
    isQuarantined: false,
    quarantinedUnitsCount: 0,
    topDefectCluster: "Suction Loss",
    clusterDefectPercentage: 55,
    gmvAtRiskInr: 47840,
  },
  "BATCH-2026-DR": {
    batchId: "BATCH-2026-DR",
    sku: "DRS-VELVET-99",
    productName: "Velvet Elegance Evening Gown",
    vendorId: "VEND-SILK-12",
    vendorName: "SilkRoute Couture",
    totalUnitsSold: 120,
    totalReturnsReported: 4,
    historicalDefectRate: 0.033,
    currentDefectRate: 0.033,
    riskLevel: "LOW",
    isQuarantined: false,
    quarantinedUnitsCount: 0,
    topDefectCluster: "Customer Remorse",
    clusterDefectPercentage: 30,
    gmvAtRiskInr: 195960,
  }
};

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: "scenario-sole-defect",
    badge: "Systemic Defect & Quarantine",
    badgeColor: "rose",
    title: "AeroFlow Runner X — Outsole Separation",
    subtitle: "Demonstrates Multimodal Defect Verification + Return Memory Anomaly + Auto-Quarantine",
    scenarioDescription: "Customer reports outsole glue failure after 3 days. Unit economics + defect pattern triggers instant credit and activates batch quarantine on Batch #2026-08.",
    expectedOutcome: "Keep Product + Instant Credit (Saves ₹180 shipping) -> Triggers Batch Quarantine (85 units locked)",
    sampleImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
    request: {
      id: "RET-10492",
      orderId: "ORD-94821",
      customerName: "Aarav Sharma",
      customerEmail: "aarav.test@example.com",
      productName: "AeroFlow Velocity Runner X",
      productSku: "SHOE-AERO-08",
      productCategory: "Footwear",
      batchId: "BATCH-2026-08",
      vendorId: "VEND-APEX-09",
      vendorName: "Apex Footwear Ltd",
      itemPriceInr: 2499,
      productMarginInr: 210,
      reverseShippingCostInr: 180,
      customerClaimReason: "Outsole separation on first week",
      customerFreeText: "The right shoe rubber outsole completely peeled away from the heel after jogging 2km. The glue seems dried out and defective.",
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
      createdAt: new Date().toISOString(),
    }
  },
  {
    id: "scenario-zipper-defect",
    badge: "Express Replacement + Vendor Claim",
    badgeColor: "amber",
    title: "Leather Bomber Jacket — Split Zipper Teeth",
    subtitle: "High-value apparel manufacturing defect with automated supplier chargeback claim",
    scenarioDescription: "Customer reports broken metal zipper. Higher margin item warrants express replacement dispatch with courtesy store voucher.",
    expectedOutcome: "Express Replacement + Return label + INR 95,400 Vendor Dispute Notice Generated",
    sampleImage: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80",
    request: {
      id: "RET-88319",
      orderId: "ORD-55410",
      customerName: "Priya Nair",
      customerEmail: "priya.nair@example.com",
      productName: "Midnight Leather Bomber Jacket",
      productSku: "JKT-BOMB-04",
      productCategory: "Apparel",
      batchId: "BATCH-2026-04J",
      vendorId: "VEND-NORTH-04",
      vendorName: "NorthStar Apparels",
      itemPriceInr: 3499,
      productMarginInr: 1100,
      reverseShippingCostInr: 220,
      customerClaimReason: "Zipper split and stitching frayed",
      customerFreeText: "Tried to zip the jacket for the first time and the metal teeth split straight down the middle. Unusable.",
      imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&q=80",
      createdAt: new Date().toISOString(),
    }
  },
  {
    id: "scenario-sizing-exchange",
    badge: "1-Click Sizing Exchange",
    badgeColor: "cyan",
    title: "Compression Tee — Sizing Mismatch",
    subtitle: "Converts return into instantaneous exchange with AI fit recommendation",
    scenarioDescription: "Customer says Medium size feels like Small. Instead of refunding, agent issues an instant 1-click exchange link for Size Large with zero friction.",
    expectedOutcome: "1-Click Exchange Link for Size L dispatched in < 2 seconds",
    sampleImage: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
    request: {
      id: "RET-30412",
      orderId: "ORD-68219",
      customerName: "Vikram Malhotra",
      customerEmail: "vikram.m@example.com",
      productName: "ActiveFit Breathable Compression Tee",
      productSku: "TEE-ACT-11",
      productCategory: "Sportswear",
      batchId: "BATCH-2026-11T",
      vendorId: "VEND-KNIT-02",
      vendorName: "KnitCraft Global",
      itemPriceInr: 799,
      productMarginInr: 240,
      reverseShippingCostInr: 140,
      customerClaimReason: "Size fits too tight in shoulders",
      customerFreeText: "I usually wear Medium in all brands but this is extremely tight across chest and shoulders. Would love to swap for Large.",
      imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
      createdAt: new Date().toISOString(),
    }
  },
  {
    id: "scenario-low-margin-keep",
    badge: "Reverse Logistics Unit Economics",
    badgeColor: "emerald",
    title: "Phone Mount — Low Margin Reverse Shipping Avoidance",
    subtitle: "Reverse shipping (₹160) > Item Margin (₹65) -> Auto 'Keep It & Instant Credit'",
    scenarioDescription: "Item cost ₹299. Shipping it back costs ₹160 which destroys profitability. Agent issues instant store credit and tells customer to keep/recycle the item.",
    expectedOutcome: "Keep Product + ₹299 Store Credit (Avoids ₹160 wasteful reverse shipping)",
    sampleImage: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=600&auto=format&fit=crop&q=80",
    request: {
      id: "RET-44109",
      orderId: "ORD-12904",
      customerName: "Sneha Patel",
      customerEmail: "sneha.patel@example.com",
      productName: "UltraGrip Windshield Phone Mount",
      productSku: "ACC-MOUNT-01",
      productCategory: "Accessories",
      batchId: "BATCH-2026-ACC",
      vendorId: "VEND-VOLT-07",
      vendorName: "VoltGear Supplies",
      itemPriceInr: 299,
      productMarginInr: 65,
      reverseShippingCostInr: 160,
      customerClaimReason: "Suction cup doesn't stick to glass",
      customerFreeText: "The suction lever keeps loosening and falls off windshield.",
      imageUrl: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=600&auto=format&fit=crop&q=80",
      createdAt: new Date().toISOString(),
    }
  },
  {
    id: "scenario-wardrobing-fraud",
    badge: "Wardrobing & Fraud Detection",
    badgeColor: "purple",
    title: "Velvet Gown — Worn Item with Cut Tags",
    subtitle: "AI detects high fraud risk and politely routes for physical inspection",
    scenarioDescription: "Customer claims unopened/unworn, but image analysis reveals removed security tag, hem scuffs, and perfume fragrance stains.",
    expectedOutcome: "Flagged (Fraud Score: 0.88) -> Held for Human Inspection with polite verification email",
    sampleImage: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&auto=format&fit=crop&q=80",
    request: {
      id: "RET-72901",
      orderId: "ORD-99120",
      customerName: "Ananya Roy",
      customerEmail: "ananya.r@example.com",
      productName: "Velvet Elegance Evening Gown",
      productSku: "DRS-VELVET-99",
      productCategory: "Luxury Apparel",
      batchId: "BATCH-2026-DR",
      vendorId: "VEND-SILK-12",
      vendorName: "SilkRoute Couture",
      itemPriceInr: 4899,
      productMarginInr: 1800,
      reverseShippingCostInr: 250,
      customerClaimReason: "Brand new, didn't fit occasion",
      customerFreeText: "Item is totally brand new and unopened in original packaging. Requesting full immediate refund.",
      imageUrl: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&auto=format&fit=crop&q=80",
      createdAt: new Date().toISOString(),
    }
  }
];

export const INITIAL_OPERATIONAL_METRICS: OperationalImpactMetrics = {
  totalReturnsAnalyzed: 127,
  logisticsCostAvoidedInr: 18420,
  unnecessaryRefundsAvoidedInr: 9850,
  defectiveBatchesQuarantined: 3,
  unitsQuarantinedCount: 482,
  estimatedFutureLossPreventedInr: 74200,
  avgTriageTimeSeconds: 1.2,
};
